#pragma once

#if defined ORBIT_DIRECTX_11 || defined ORBIT_DIRECTX_12
#include <dinput.h>
#else

#endif

namespace orbit
{

    enum class KeyCode
    {
#if defined ORBIT_DIRECTX_11 || defined ORBIT_DIRECTX_12
        KEY_A = DIK_A,
        KEY_B = DIK_B,
        KEY_C = DIK_C,
        KEY_D = DIK_D,
        KEY_E = DIK_E,
        KEY_F = DIK_F,
        KEY_G = DIK_G,
        KEY_H = DIK_H,
        KEY_I = DIK_I,
        KEY_J = DIK_J,
        KEY_K = DIK_K,
        KEY_L = DIK_L,
        KEY_M = DIK_M,
        KEY_N = DIK_N,
        KEY_O = DIK_O,
        KEY_P = DIK_P,
        KEY_Q = DIK_Q,
        KEY_R = DIK_R,
        KEY_S = DIK_S,
        KEY_T = DIK_T,
        KEY_U = DIK_U,
        KEY_V = DIK_V,
        KEY_W = DIK_W,
        KEY_X = DIK_X,
        KEY_Y = DIK_Y,
        KEY_Z = DIK_Z,
        KEY_0 = DIK_0,
        KEY_1 = DIK_1,
        KEY_2 = DIK_2,
        KEY_3 = DIK_3,
        KEY_4 = DIK_4,
        KEY_5 = DIK_5,
        KEY_6 = DIK_6,
        KEY_7 = DIK_7,
        KEY_8 = DIK_8,
        KEY_9 = DIK_9,
        KEY_LSHIFT = DIK_LSHIFT,
        KEY_RSHIFT = DIK_RSHIFT,
        KEY_LCTRL = DIK_LCONTROL,
        KEY_RCTRL = DIK_RCONTROL,
        KEY_LALT = DIK_LALT,
        KEY_RALT = DIK_RALT,
        KEY_LWIN = DIK_LWIN,
        KEY_RWIN = DIK_RWIN,
        KEY_RETURN = DIK_RETURN,
        KEY_BACKSPACE = DIK_BACKSPACE,
        KEY_TAB = DIK_TAB,
        KEY_F1 = DIK_F1,
        KEY_F2 = DIK_F2,
        KEY_F3 = DIK_F3,
        KEY_F4 = DIK_F4,
        KEY_F5 = DIK_F5,
        KEY_F6 = DIK_F6,
        KEY_F7 = DIK_F7,
        KEY_F8 = DIK_F8,
        KEY_F9 = DIK_F9,
        KEY_F10 = DIK_F10,
        KEY_F11 = DIK_F11,
        KEY_F12 = DIK_F12,
        KEY_ESCAPE = DIK_ESCAPE,
        KEY_LEFT = DIK_LEFTARROW,
        KEY_RIGHT = DIK_RIGHTARROW,
        KEY_UP = DIK_UPARROW,
        KEY_DOWN = DIK_DOWNARROW,
        KEY_NUMLEFT = DIK_LEFT,
        KEY_NUMRIGHT = DIK_LEFT,
        KEY_NUMUP = DIK_LEFT,
        KEY_NUMDOWN = DIK_LEFT,
        KEY_SPACE = DIK_SPACE,
        KEY_PERIOD = DIK_PERIOD,
        KEY_COMMA = DIK_COMMA,
        KEY_COLON = DIK_COLON,
        KEY_SEMICOLON = DIK_SEMICOLON,
        KEY_UNDERLINE = DIK_UNDERLINE,

        KEY_PLUS = DIK_ADD,
        KEY_MINUS = DIK_SUBTRACT,
        KEY_ASTERISK = DIK_MULTIPLY,
        
        KEY_SLASH = DIK_SLASH,
        KEY_BACKSLASH = DIK_BACKSLASH,
        KEY_NUMPLUS = DIK_NUMPADPLUS,
        KEY_NUMMINUS = DIK_NUMPADMINUS,
        KEY_NUMASTERISK = DIK_NUMPADSTAR,
        KEY_NUMSLASH = DIK_NUMPADSLASH,
        KEY_NUMPERIOD = DIK_NUMPADPERIOD,
        KEY_NUMCOMMA = DIK_NUMPADCOMMA,
        KEY_NUMENTER = DIK_NUMPADENTER,
        KEY_NUMEQUALS = DIK_NUMPADEQUALS,
        KEY_NUMLOCK = DIK_NUMLOCK,
        KEY_NUM0 = DIK_NUMPAD0,
        KEY_NUM1 = DIK_NUMPAD1,
        KEY_NUM2 = DIK_NUMPAD2,
        KEY_NUM3 = DIK_NUMPAD3,
        KEY_NUM4 = DIK_NUMPAD4,
        KEY_NUM5 = DIK_NUMPAD5,
        KEY_NUM6 = DIK_NUMPAD6,
        KEY_NUM7 = DIK_NUMPAD7,
        KEY_NUM8 = DIK_NUMPAD8,
        KEY_NUM9 = DIK_NUMPAD9,
        KEY_CIRCUMFLEX = DIK_CIRCUMFLEX,
        KEY_GRAVE = DIK_GRAVE,
        KEY_APOSTROPHE = DIK_APOSTROPHE,
        KEY_DELETE = DIK_DELETE,
        KEY_END = DIK_END,
        KEY_EQUALS = DIK_EQUALS,
        KEY_INSERT = DIK_INSERT,
        KEY_LBRACKET = DIK_LBRACKET,
        KEY_RBRACKET = DIK_RBRACKET,
        KEY_PAGEUP = DIK_PGUP,
        KEY_PAGEDOWN = DIK_PGDN,
#else

#endif
    };
}